replicate/monobase

script/debug.sh
to allow specifying various parameters via env vars.
=> Minor tweaks to debug script

.dockerignore, .github/workflows/ci.yml, Dockerfile
mostly so that the generated version metadata is correct.
Connected to PLAT-589
=> Build and install from sdist via uv

Dockerfile, pyproject.toml, script/build, script/build-mini, script/build-runtime, src/monobase/build.sh, src/monobase/util.py, uv.lock
and make sure build-time and runtime account for installation of third-party dependencies
Connected to PLAT-555
=> Configure logs with structlog

src/monobase/build.py, src/monobase/user.py
* Allow monobases to be created with no defined cuda version
=> Support no CUDA version specification

src/monobase/build.py, src/monobase/monogen.py, src/monobase/update.py, src/monobase/user.py, src/monobase/util.py, src/monobase/uv.py
* Allow sending torch version as none
* If this is none then torch will not be installed in the venv
* This is due to not all cog users wanting to install torch, so if they don’t we may as well not install it into the venv
=> Support empty torch versions

Dockerfile, mini.Dockerfile, script/build-prod, script/test, script/test-mini, src/monobase/build.py, src/monobase/run.sh
- **Fix typo**
- **Generalize build.sh**
=> Minor fixes

mini.Dockerfile, requirements-user.txt, src/monobase/build.py, src/monobase/user.py
- **Add /var/cache/monobase to mini image build**
- **Fix mini & CPU torch handling**
- **Use Torch index for user requirements**
=> Various mini build fixes

src/monobase/build.py, src/monobase/cog.py
=> Pass python_versions as list to install_cogs

src/monobase/pget
Standardize the flow to pull files from `FUSE` so we can do authorization when necessary.
This should be a change that is verifiable by eye.
=> Standardize flow to request files from fuse-rpc

src/monobase/run.sh
We use the `run.sh` wrapper for `monobase.{build,user}`. We should always install latest `uv` & `pget` on build. `monobase.user` is always run as a follow up step to `monobase.build` in multi-layer cog builds so it's OK to skip if they exist.
Also changed it to download first then `mv` for atomicity.
=> Always install uv & pget in monobase.build

script/test-pget, src/monobase/pget
Also added a test, but it depends on internal component and is not runnable in CI. Verified locally that it works.
=> Rewrite pget wrapper in python

src/monobase/pget
- **Fix dir builtin warning**
- **Normalize HF CDN URLs in pget fingerprint**
=> Normalize HF CDN URLs in pget fingerprint

src/monobase/activate.sh, src/monobase/cog.py, src/monobase/monogen.py
* Install it in cog venvs so it's avaiable to torch-less models
* Install latest custom wheel if available
=> Install custom hf_transfer

Dockerfile, script/test-pget, src/monobase/pget.py, src/monobase/run.sh
- **Add .py suffix to pget wrapper for ruff**
- **Normalize S3 presigned URL in pget.py**
=> Normalize S3 presigned URL in pget.py

.github/workflows/ci.yml, script/test-apt, script/test-mini, script/test-user
- **Fix test script comments**
- **Add test for apt.sh**
=> Add test for apt.sh'

Dockerfile, apt-dependencies.txt
* Allow `fairseq` to be installed with an updated GCC
=> Update GCC to v12

packages/build.py
=> Mount script when building packages

packages/README.md, packages/build.py, packages/fairseq.sh, packages/mid-splatting.sh, packages/test.sh
- **More build.py fixes**
- **Add test for custom packages**
=> Packaging improvements

packages/Hunyuan3D-2.sh, packages/README.md, packages/fairseq.sh, packages/mid-splatting.sh, packages/test.sh
- **Tweak package script output handling**
- **Add Hunyuan3D-2.sh**
=> Add Hunyuan3D-2 package script

script/test-user, src/monobase/monogen.py
- **Cover more local package install cases**
- **Add cython to base venv for youtokentome, etc.**
=> Add cython to base venv for youtokentome, etc.

script/debug, script/test, script/test-mini, script/test-user, src/monobase/cog.py
For predictor code that checks importlib.metadata.version("cog")
=> Create cog-*.dist-info & metadata

src/monobase/pget.py
* Check if `PGET_KNOWN_WEIGHTS_DIR` is actually set
* Do not check `.tar` extension, irrelevant now since we check Hermes + local cache already
* Other style fixes & clarifications.
=> Fix up pget.py

src/monobase/pget.py
* For both weights dir and FUSE cases i.e. not falling back to pget-bin
* Print message
* Send metrics
=> Tweak pget logging & metrics
