replicate/monobase

src/monobase/monogen.py
src/monobase/torch.py
src/monobase/uv.py

Install torch nightly builds with `@ https://...` so that older builds removed from index after 60 days are still installable.

Install torch nightly from wheel URLs

---

src/monobase/__main__.py

(like I just did) that tells a human (like me) what they probably wanted to do instead.

Add a docs-only shim in case of running `python -m monobase`

---

.gitignore
pyproject.toml
script/test
script/test-mini
src/monobase/build.py
src/monobase/cog.py
src/monobase/cuda.py
src/monobase/user.py
src/monobase/util.py
src/monobase/uv.py

so that we can pass along more context through `director` and generally depend on more than an empty file.
~**Please note**: this also includes a behavior change to `is_done` that no longer deletes the directory tree when `.done` is not present. I couldn't come up with a reason for why we would want this outside of testing. I'm happy to learn that it's important and we should keep it that way 😇 (although if it needs to be kept that way then I'd like it to have a different name).~
**Update**: What was previously `monobase.util:is_done` is now `monobase.util:require_done_or_rm`
Connected to PLAT-555

Include timestamp and span-compatible attributes in done files

---

src/monobase/env.sh

* As far as I can tell monobase `build.py` enforces the creation of the `latest` symlink, so there is no need to keep this find code around

Monobase should always be creating a latest dir

---

src/monobase/activate.sh

to be passed along to other observability layers.
Connected to PLAT-589

Export `R8_ATTRIBUTES_FILES` in model env

---

src/monobase/build.sh

so that scheduling can account for the ready state of the monobase pod.

Write monobase done label to kubernetes node feature discovery

---

src/monobase/build.sh

given `nfd-worker` complaining
```
ignoring invalid feature value monobase-done=2024-12-10T23:03:11+00:00: [a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character
```
Connected to PLAT-689

Set `done` as a valid alphanumeric label

---

script/test
script/test-mini
src/monobase/build.py
src/monobase/build.sh
src/monobase/monogen.py
src/monobase/util.py

So that the latest generation being complete will add the necessary node label. I also moved the node feature discovery labeling into `monobase.build` and dropped the `sleep infinity` with the intent of changing the daemonset to run `monobase.build` in an init container and then switching the main container to run `pause` as is currently done for the `nfd-cgroup-version` component.
Connected to PLAT-689

Mark done on latest; move feature labeling into build

---

.github/workflows/ci.yml
Dockerfile
apt-dependencies.txt
runtime.Dockerfile
script/build-runtime
script/debug

with minimal files present so as to minimize possibility of affecting models.
This is in preparation for introducing non-stdlib dependencies to monobase for the purpose of improving observability.
Connected to PLAT-555
Depends on replicate/actions#36

Build and push `monobase-runtime` image

---

pyproject.toml
script/test
src/monobase/build.py
src/monobase/build.sh
src/monobase/cog.py
src/monobase/cuda.py
src/monobase/monogen.py
src/monobase/optimize.py
src/monobase/prune.py
src/monobase/update.py
src/monobase/user.py
src/monobase/util.py
src/monobase/uv.py
uv.lock

with my intention being that these traces will be a longer-lived and more queryable record than what we currently have.
Connected to PLAT-590
Example trace view via [jaeger](https://www.jaegertracing.io):

Adding a round of OTEL around `build`

---

src/monobase/build.py
src/monobase/util.py

instead of assuming a specific file prefix.
Connected to PLAT-566

Look up requirements paths via python package path

---

src/monobase/cog.py

* When building a monobase on the cog client we feed cog in via a wheel file rather than an http
or pypi version

Support cog installation via file://

---

kubernetes/oneoff/kustomization.yaml
kubernetes/oneoff/pod.yaml
script/build-prod
script/run-oneoff-pod

as with replicate/web admin tooling. My eventual goal here is to run monobase builds in each cluster as part of CI on the `main` branch instead of managing the separate daemonset in replicate/cluster.
Connected to PLAT-582

Add tooling to run "oneoff" pods

---

script/test
src/monobase/activate.sh
src/monobase/cog.py
uv.lock

`coglet` is a drop in replacement for vanilla cog. The wheel file contains Go `cog-server` binary and `cog.server.http` module wrapper.
To use `coglet` instead of `cog`, we specify `--cog-versions` & `R8_COG_VERSION` as one of:
* `https://github.com/replicate/cog-runtime/releases/download/v<version>/coglet-<version>-py3-none-any.whl`
* `coglet==<version>`

Support cog-runtime

---

.github/workflows/ci.yml
Dockerfile

Connected to PLAT-566
Connected to PLAT-768
Depends on replicate/registry-proxy#93 
Depends on replicate/infra#295 (or something like it)

Push monobase and monobase-runtime images to r8.im

---

src/monobase/build.py

Seeing these warnings from OTEL:
```
{"logger": "opentelemetry.attributes", "timestamp": "2025-01-10T00:53:36.291879Z", "severity": "WARNING", "message": "Invalid type dict for attribute 'cuda' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those
types"}
{"logger": "opentelemetry.attributes", "timestamp": "2025-01-10T00:53:36.291982Z", "severity": "WARNING", "message": "Invalid type dict for attribute 'cudnn' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those
types"}
{"logger": "opentelemetry.attributes", "timestamp": "2025-01-10T00:53:36.292018Z", "severity": "WARNING", "message": "Invalid type dict for attribute 'python' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of thos
e types"} …
```

Fix OTEL dict attribute warning

---

src/monobase/activate.sh

* This fixes the following issues: /opt/r8/monobase/activate.sh: line 71: R8_CUDA_VERSION: unbound variable
* We don’t define these variables so we need to handle the cases where they aren’t set.

Fix not having ENV vars defined

---

src/monobase/activate.sh

* This allows a program using the activation to set the required verbosity level of the activation script.
* It is necessary due to how cog relies on strict stdout in some of its processes.

Allow VERBOSE env var to control output

---

script/build-mini-image
src/monobase/apt.sh

* Use monobase:latest to build apt tarball
* Compression codecs are already in monobase:latest
* Use --download-only and remove apt.conf.d hack

Tweak APT layer

---

script/test
script/test-mini

`/srv/r8/monobase` might be read-only in prod model pods.

Make test mounts read-only

---

src/monobase/tar.sh

* We do not need this noisiness in fast push

Remove verbose output from tar monobase

---

src/monobase/monogen.py
src/monobase/user.py
uv.lock

Some packages like `flash-attn` needs access to `torch` and `nvcc` during
installation. Expose monobase venv and `CUDA_HOME` in those cases.

Expose monobase venv during user venv pip install

---

.github/workflows/ci.yml
script/latest_coglet.py
script/test-mini
script/test-user
src/monobase/activate.sh
src/monobase/update.py
src/monobase/user.py
src/monobase/util.py

- **Only update matrix.json for prod environment**
- **Stop checking coglet version in mini test**
- **Remove unused requirements-user.txt from mini build**
- **Capture cog/coglet==latest/version in activate.sh**
- **Print uv compile error directly**
- **Limit split when parsing requirements**
- **Support local path in monobase.user requirements.txt**
- **Add test for user layer build**

Improve user layer build & test

---

src/monobase/run.sh

run.sh runs the monobase scripts which might call other Python scripts
in sub-shells, e.g. pget.py. Append .venv/bin, i.e. the same one running
monobase, to PATH for these scripts.

Add .venv/bin to PATH in run.sh

---

src/monobase/cog.py

* To potentially fix the issue of: No such file or directory (os error 2)
* Should make sure all the local directories exist before utilising the cache
* This will only be for cog/hf-transfer so should be light

Add —refresh-package to uv pip install of cog

---

script/test-user
src/monobase/user.py
src/monobase/uv.py

- **Use unsafe-first-match index-strategy for user venv**
- **Support uv pip compile --override**
`unsafe-first-match` so that we are not constrained by older packages in pytorch.org index. We use pre-frozen Torch requirements and exclude them from user venv anyway.
`--override` can be used to bypass irreconcilable conflicts.
For conflicts against base venv, e.g. `pyreft` wants `numpy==1.26.4` but base venv has `numpy==1.26.3`, we must pin it to the latter as base venv has higher precedence.
```
numpy==1.26.3
```
For conflicts in user's `requirements.txt`, e.g. user wants package `A` & `B` that want `C==1.0.0` vs `C==1.1.0`, we have to pick one and verify that it works with both.

Allow more flexibility in user venv build

---

src/monobase/activate.sh
src/monobase/run.sh
src/monobase/user.py

Set `CUDA_HOME` and `PYTHONPATH` in `activate.sh` which is sourced before running `monobase.user`.
However, we use a temp `/var/tmp.venv` & `PYTHONPATH` to run `monobase.*`. Therefore we need to save the actual `PYTHONPATH` of runtime environment in `R8_PYTHONPATH` and restore it in `monobase.user`.

Consolidate env vars in activate.sh

---

src/monobase/user.py

Regression from #125.
We should only warn if a package has different version in user venv vs monobase venv, and always exclude it to avoid bloating the user tarball.

Fix monobase exclusion

---

src/monobase/pget.py

When we find a prefix that would be cached through Hermes, use it instead of FUSE. In general because of all the layers of indirection, we see slowness in FUSE that we think would be faster through Hermes instead, plus cuts down on some complexity

Fallback to regular pget when cached prefix

---

src/monobase/pget.py
src/monobase/refresh_files.py

One of our experiments will be taking the top 1-2 TB of files and hosting them on disk. Rather than downloading them every time, we'll simply symlink them in if they are on disk. This idea should gain us pretty significant speedup as a whole since a significant proportion of our traffic comes from like 15-20 models.

Support maintaining top k files on disk

---

src/monobase/refresh_files.py

* Support sleep interval
* Remove `--upstream-url` - we should just pass `PGET_*` env vars like in model pods.
* Logging - turns out we have to install uv & monobase package 1st via `run.sh` so it's OK to have dependencies
* Rough edges, bug fixes, etc.

Tweak refresh_files.py

---

src/monobase/pget.py

Previously, we instantly defaulted to regular pget if FUSE didn't exist. Now, we should check if the file is in local cache, then check if FUSE exists

Move FUSE check
